DROP TABLE IF EXISTS ladder;

CREATE TABLE ladder(
id SERIAL PRIMARY KEY,
users_id INTEGER NOT NULL REFERENCES users(id),
company_id INTEGER NOT NULL,
ranking INTEGER NOT NULL,
first VARCHAR(200) NOT NULL CHECK (first <> ''),
last VARCHAR(200) NOT NULL CHECK (last <> ''),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

